# Generated by Django 3.0.4 on 2020-03-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=100)),
                ('large_p', models.FloatField()),
                ('regular_p', models.FloatField()),
                ('small_p', models.FloatField()),
                ('speciality', models.FloatField(default=False)),
            ],
        ),
    ]
