# Generated by Django 3.0.4 on 2020-03-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0005_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
